### ISSUE TITLE
Change emoji reaction for error messages

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/jack#38]
# Expected Behavior

jack should react with a different emoji when an error occurs.

# Current Behavior

Jack reacts to all messages with the same emoji(CUSTOM JACK EMOJI).

## Steps to Reproduce

1. Join SRMKZILLA's discord server: https://community.srmkzilla.net
2. Write gibberish so that the bot throws an error.

When no error occurs:

![image](https://user-images.githubusercontent.com/74819565/135883782-7a0efe24-73b1-49d0-8bae-3f7f654599a6.png)

When an error occurs:

![image](https://user-images.githubusercontent.com/74819565/135883719-3015a38c-acdb-4045-b5c7-2137cf774f99.png)

**Comment by lakshya-dhariwal** [comment]
Different emoji for different types of error or just a emoji ( different from default jack ) for all errors?

**Comment by shawshankkumar** [comment]
> Different emoji for different types of error or just a emoji ( different from default jack ) for all errors?

The latter. A red circle or a cross would do fine in case of an error. If you are interested, let me know, I'll assign it to you.
