### ISSUE TITLE
Include Prettier config to project

### ISSUE THREAD

**Issue by lakshya-dhariwal** [srm-kzilla/jack#48]
Currently the project lacks a prettier config file. 
A Prettier config file is to make sure that when a project is copied to another computer, Prettier's behaviour stays the same. Otherwise, Prettier wouldn't be able to guarantee that everybody in a team gets the same consistent results. This leads to unnecessary changes during each PR.

**Comment by shawshankkumar** [comment]
@alvinbengeorge
