### ISSUE TITLE
Take an additional parameter from database for certificate generation

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/jack#51]
# Expected Behavior

Allow left, right and center instead of hardcoded center align.

SRMKZILLA Uses jimp to generate certificates for its events. Currently all texts are center aligned by default. https://github.com/srm-kzilla/jack/blob/master/src/service/certificate-service.ts

We want this to be toggled using database. LEFT, RIGHT or CENTER are the options to be given.

**Comment by meltedhyperion** [comment]
Issue fixed! 
Refer to PR #53
